---

- name: Ensure Apache is running
  service: name=apache2 state=started
  tags:
    - services_apache

- name: Ensure MySQL is running
  service: name=mysql state=started
  tags:
    - services_mysql

- name: Ensure Fail2Ban is running
  service: name=fail2ban state=started
  tags:
    - services_fail2ban
